### PR TITLE
Adding linux_admin_username variable to be able to change admin_username

### PR DESCRIPTION
**Pull request by ruzickap**

### CODE REVIEW

**Review by trawler — COMMENTED** [review]
If you’re adding an input variable to terraform it needs to be defined, configured, and sent by the installer. 
Where would this var come from? Will it be taken from the installer’s yaml config?
I tend to think that it adds unnecessary complexity, since this var wouldn’t be that important to the operator. Many similar projects have a non-configurable dedicated username for operators and the need to customize it doesn’t come up very often. 
I can suggest however to rename it to a project-specific name, like “cna”.

**Comment by ruzickap** [comment]
I believe it should not be "filled" by installer, because this variable `linux_admin_username` is defined in `variables.tf` and has it's own "default value": `default = "ubuntu"`.
I just don't like hardcoded strings in the code - I always prefer to put them in `variables.tf` and set the default value there.

**Comment by trawler** [comment]
generally you would be correct, in cases where terraform is the only tool that manages the configuration, but in the installer case, I believe that the configuration should be owned solely by the installer. Meaning, that any input variables should also be configurable in the installer. Otherwise, you will run into cases where setting defaults masks bugs in the installer code...

**Comment by ruzickap** [comment]
Ok... It's clear now...
Closing...

**Pull request closed without merging**
